fastlane_version "1.104.0"

opt_out_usage

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan(
      project: "PROJ.xcodeproj",
      configuration: "Debug",
      scheme: "SCHEME",
      clean: true,
      output_directory: "./build/test_output",
      output_types: "html,junit"
      )
  end

  desc "Build app"
  lane :build do
    output_name = 'NAME'
    git_branch = (ENV['GIT_BRANCH'] || '').gsub('origin/', '')
    git_commit = (ENV['GIT_COMMIT'] || '')[0, 7]
    if (git_branch && git_commit)
      output_name = "#{output_name}_#{git_branch}_#{git_commit}"
    end

    gym(
      project: "PROJ.xcodeproj",
      configuration: "Debug",
      scheme: "SCHEME",
      clean: true,
      output_directory: "./build",
      output_name: "#{output_name}.ipa",
      #codesigning_identity: "iPhone Developer: Name (AAAAA99999)",
      #xcargs: "PROVISIONING_PROFILE={PROFILE}",
      #use_legacy_build_api: true
      export_options: "fastlane/exportPlist-dev.plist"
      )
  end
end
