fastlane_version "2.53.1"

opt_out_usage
default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: "PROJ.xcworkspace",
      configuration: "Debug",
      scheme: "SCHEME",
      clean: true,
      output_directory: "./build/test_output",
      output_types: "html,junit"
      )
  end

  desc "Build app"
  lane :build do
    output_name = 'NAME'
    git_branch = (ENV['BRANCH_NAME'] || '').gsub('origin/', '')
    git_commit = (ENV['GIT_COMMIT'] || '')[0, 7]
    if (git_branch && git_commit)
      output_name = "#{output_name}_#{git_branch}_#{git_commit}"
    end

    gym(
      workspace: "PROJ.xcworkspace",
      configuration: "Release",
      scheme: "SCHEME",
      clean: true,
      output_directory: "./build",
      output_name: "#{output_name}.ipa",
      export_options: "fastlane/exportPlist.plist",
      )
  end
end

